from importlib import metadata

from smscode.async_client import AsyncSmscodeClient
from smscode.client import SmscodeClient
from smscode.errors import (
    CancelTooEarlyError,
    ConflictError,
    ForbiddenError,
    FxRateUnavailableError,
    IdempotencyKeyReuseError,
    InsufficientBalanceError,
    InternalError,
    InvalidMoneyError,
    InvalidResponseError,
    NetworkError,
    NoOfferAvailableError,
    NotFoundError,
    OrderTerminalError,
    OtpTimeoutError,
    PayloadTooLargeError,
    ProviderError,
    RateLimitError,
    RequestCancelledError,
    RequestInProgressError,
    ServiceUnavailableError,
    SmscodeError,
    TempBannedError,
    TimeoutError,
    UnauthorizedError,
    ValidationError,
    map_error,
)
from smscode.idempotency import (
    IDEMPOTENCY_KEY_PATTERN,
    is_valid_idempotency_key,
    resolve_idempotency_key,
)
from smscode.models import (
    BalanceV1,
    BalanceV2,
    CancelResult,
    CancelResultV2,
    Country,
    CreatedOrder,
    CreateOrderResult,
    CreateOrderResultV1,
    CreateOrderResultV2,
    ExchangeRate,
    FinishResult,
    Operator,
    Order,
    OrderCapabilities,
    OrdersList,
    OrdersListV2,
    Product,
    ProductsPage,
    ProductsPageV1,
    ProductsPageV2,
    ProductV2,
    ReactivateOptions,
    ReactivateOptionsV2,
    ResendResult,
    Service,
    V2Fx,
    WebhookConfig,
    WebhookTestResult,
)
from smscode.money import Money, parse_money
from smscode.retry import RetryPolicy, async_with_retry, with_retry
from smscode.types import ApiResult, RequestOptions
from smscode.wait import OtpResult, async_wait_for_otp, wait_for_otp
from smscode.webhook import (
    WebhookEvent,
    is_webhook_event,
    parse_webhook_event,
    verify_webhook_signature,
)

VERSION = metadata.version("smscode")
__version__ = VERSION


__all__ = [
    "IDEMPOTENCY_KEY_PATTERN",
    "VERSION",
    "ApiResult",
    "AsyncSmscodeClient",
    "BalanceV1",
    "BalanceV2",
    "CancelResult",
    "CancelResultV2",
    "CancelTooEarlyError",
    "ConflictError",
    "Country",
    "CreateOrderResult",
    "CreateOrderResultV1",
    "CreateOrderResultV2",
    "CreatedOrder",
    "ExchangeRate",
    "FinishResult",
    "ForbiddenError",
    "FxRateUnavailableError",
    "IdempotencyKeyReuseError",
    "InsufficientBalanceError",
    "InternalError",
    "InvalidMoneyError",
    "InvalidResponseError",
    "Money",
    "NetworkError",
    "NoOfferAvailableError",
    "NotFoundError",
    "Operator",
    "Order",
    "OrderCapabilities",
    "OrderTerminalError",
    "OrdersList",
    "OrdersListV2",
    "OtpResult",
    "OtpTimeoutError",
    "PayloadTooLargeError",
    "Product",
    "ProductV2",
    "ProductsPage",
    "ProductsPageV1",
    "ProductsPageV2",
    "ProviderError",
    "RateLimitError",
    "ReactivateOptions",
    "ReactivateOptionsV2",
    "RequestCancelledError",
    "RequestInProgressError",
    "RequestOptions",
    "ResendResult",
    "RetryPolicy",
    "Service",
    "ServiceUnavailableError",
    "SmscodeClient",
    "SmscodeError",
    "TempBannedError",
    "TimeoutError",
    "UnauthorizedError",
    "V2Fx",
    "ValidationError",
    "WebhookConfig",
    "WebhookEvent",
    "WebhookTestResult",
    "__version__",
    "async_wait_for_otp",
    "async_with_retry",
    "is_valid_idempotency_key",
    "is_webhook_event",
    "map_error",
    "parse_money",
    "parse_webhook_event",
    "resolve_idempotency_key",
    "verify_webhook_signature",
    "wait_for_otp",
    "with_retry",
]
